export interface Country {
  code: string; // ISO 3166-1 alpha-2
  name: string;
  capital: string;
  lat: number;
  lng: number;
  governmentType: string;
  population: number; // approx, millions
}

// Starter set — expand this list over time. Each entry needs only
// coordinates + basic facts; power-structure detail arrives in M14.
export const countries: Country[] = [
  {
    code: "US",
    name: "United States",
    capital: "Washington, D.C.",
    lat: 38.9,
    lng: -77.0,
    governmentType: "presidential",
    population: 335,
  },
  {
    code: "CN",
    name: "China",
    capital: "Beijing",
    lat: 39.9,
    lng: 116.4,
    governmentType: "one_party_state",
    population: 1412,
  },
  {
    code: "IN",
    name: "India",
    capital: "New Delhi",
    lat: 28.6,
    lng: 77.2,
    governmentType: "parliamentary",
    population: 1428,
  },
  {
    code: "RU",
    name: "Russia",
    capital: "Moscow",
    lat: 55.75,
    lng: 37.6,
    governmentType: "semi_presidential",
    population: 144,
  },
  {
    code: "GB",
    name: "United Kingdom",
    capital: "London",
    lat: 51.5,
    lng: -0.13,
    governmentType: "constitutional_monarchy",
    population: 68,
  },
  {
    code: "FR",
    name: "France",
    capital: "Paris",
    lat: 48.85,
    lng: 2.35,
    governmentType: "semi_presidential",
    population: 68,
  },
  {
    code: "DE",
    name: "Germany",
    capital: "Berlin",
    lat: 52.52,
    lng: 13.4,
    governmentType: "parliamentary",
    population: 84,
  },
  {
    code: "JP",
    name: "Japan",
    capital: "Tokyo",
    lat: 35.68,
    lng: 139.75,
    governmentType: "constitutional_monarchy",
    population: 123,
  },
  {
    code: "BR",
    name: "Brazil",
    capital: "Brasília",
    lat: -15.79,
    lng: -47.88,
    governmentType: "presidential",
    population: 216,
  },
  {
    code: "ZA",
    name: "South Africa",
    capital: "Pretoria",
    lat: -25.75,
    lng: 28.19,
    governmentType: "parliamentary",
    population: 60,
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    capital: "Riyadh",
    lat: 24.71,
    lng: 46.68,
    governmentType: "absolute_monarchy",
    population: 36,
  },
  {
    code: "IR",
    name: "Iran",
    capital: "Tehran",
    lat: 35.7,
    lng: 51.4,
    governmentType: "theocracy",
    population: 89,
  },
  {
    code: "IL",
    name: "Israel",
    capital: "Jerusalem",
    lat: 31.77,
    lng: 35.21,
    governmentType: "parliamentary",
    population: 9.7,
  },
  {
    code: "TR",
    name: "Turkey",
    capital: "Ankara",
    lat: 39.93,
    lng: 32.86,
    governmentType: "presidential",
    population: 85,
  },
  {
    code: "UA",
    name: "Ukraine",
    capital: "Kyiv",
    lat: 50.45,
    lng: 30.52,
    governmentType: "presidential",
    population: 37,
  },
  {
    code: "KP",
    name: "North Korea",
    capital: "Pyongyang",
    lat: 39.03,
    lng: 125.75,
    governmentType: "one_party_state",
    population: 26,
  },
  {
    code: "KR",
    name: "South Korea",
    capital: "Seoul",
    lat: 37.57,
    lng: 126.98,
    governmentType: "presidential",
    population: 51,
  },
  {
    code: "TW",
    name: "Taiwan",
    capital: "Taipei",
    lat: 25.03,
    lng: 121.57,
    governmentType: "presidential",
    population: 23,
  },
  {
    code: "PK",
    name: "Pakistan",
    capital: "Islamabad",
    lat: 33.68,
    lng: 73.05,
    governmentType: "parliamentary",
    population: 240,
  },
  {
    code: "EG",
    name: "Egypt",
    capital: "Cairo",
    lat: 30.04,
    lng: 31.24,
    governmentType: "presidential",
    population: 112,
  },
  {
    code: "NG",
    name: "Nigeria",
    capital: "Abuja",
    lat: 9.08,
    lng: 7.4,
    governmentType: "presidential",
    population: 224,
  },
  {
    code: "AU",
    name: "Australia",
    capital: "Canberra",
    lat: -35.28,
    lng: 149.13,
    governmentType: "constitutional_monarchy",
    population: 26,
  },
  {
    code: "CA",
    name: "Canada",
    capital: "Ottawa",
    lat: 45.42,
    lng: -75.7,
    governmentType: "constitutional_monarchy",
    population: 39,
  },
  {
    code: "MX",
    name: "Mexico",
    capital: "Mexico City",
    lat: 19.43,
    lng: -99.13,
    governmentType: "presidential",
    population: 128,
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    capital: "Abu Dhabi",
    lat: 24.47,
    lng: 54.37,
    governmentType: "absolute_monarchy",
    population: 9.4,
  },
];

export function getCountryByCode(code: string): Country | undefined {
  return countries.find((c) => c.code === code);
}
