export interface PlaceToVisit {
  name: string;
  lat: number;
  lng: number;
  country?: string;
  description?: string;
}

export const placesToVisit: PlaceToVisit[] = [
  {
    name: "Eiffel Tower",
    lat: 48.8584,
    lng: 2.2945,
    country: "France",
    description: "Iconic iron lattice tower in Paris",
  },
  {
    name: "Taj Mahal",
    lat: 27.1751,
    lng: 78.0421,
    country: "India",
    description: "Marble mausoleum in Agra",
  },
  {
    name: "Great Wall of China",
    lat: 40.4319,
    lng: 116.5704,
    country: "China",
    description: "Ancient fortification spanning northern China",
  },
  {
    name: "Machu Picchu",
    lat: -13.1631,
    lng: -72.545,
    country: "Peru",
    description: "15th-century Inca citadel in the Andes",
  },
  {
    name: "Colosseum",
    lat: 41.8902,
    lng: 12.4922,
    country: "Italy",
    description: "Ancient Roman amphitheatre in Rome",
  },
  {
    name: "Petra",
    lat: 30.3285,
    lng: 35.4444,
    country: "Jordan",
    description: "Rose-red city carved into rock",
  },
  {
    name: "Christ the Redeemer",
    lat: -22.9519,
    lng: -43.2105,
    country: "Brazil",
    description: "Art Deco statue overlooking Rio de Janeiro",
  },
  {
    name: "Sydney Opera House",
    lat: -33.8568,
    lng: 151.2153,
    country: "Australia",
    description: "Multi-venue performing arts centre",
  },
  {
    name: "Pyramids of Giza",
    lat: 29.9792,
    lng: 31.1342,
    country: "Egypt",
    description: "Ancient pyramid complex on the Giza plateau",
  },
  {
    name: "Santorini",
    lat: 36.3932,
    lng: 25.4615,
    country: "Greece",
    description: "Volcanic island with white-washed buildings",
  },
  {
    name: "Angkor Wat",
    lat: 13.4125,
    lng: 103.867,
    country: "Cambodia",
    description: "Massive temple complex in Siem Reap",
  },
  {
    name: "Mount Fuji",
    lat: 35.3606,
    lng: 138.7274,
    country: "Japan",
    description: "Active stratovolcano and sacred symbol",
  },
  {
    name: "Grand Canyon",
    lat: 36.1069,
    lng: -112.1129,
    country: "USA",
    description: "Steep-sided canyon carved by the Colorado River",
  },
  {
    name: "Sagrada Família",
    lat: 41.4036,
    lng: 2.1744,
    country: "Spain",
    description: "Gaudí's unfinished basilica in Barcelona",
  },
  {
    name: "Banff National Park",
    lat: 51.4968,
    lng: -115.9281,
    country: "Canada",
    description: "Rocky Mountain wilderness with turquoise lakes",
  },
  {
    name: "Victoria Falls",
    lat: -17.9243,
    lng: 25.8572,
    country: "Zambia / Zimbabwe",
    description: "Largest curtain of falling water on Earth",
  },
  {
    name: "Dubrovnik Old Town",
    lat: 42.6507,
    lng: 18.0944,
    country: "Croatia",
    description: "Walled medieval city on the Adriatic",
  },
  {
    name: "Bora Bora",
    lat: -16.5004,
    lng: -151.7415,
    country: "French Polynesia",
    description: "Small South Pacific island with a turquoise lagoon",
  },
  {
    name: "Reykjavik",
    lat: 64.1466,
    lng: -21.9426,
    country: "Iceland",
    description: "Northernmost capital, gateway to auroras",
  },
  {
    name: "Cappadocia",
    lat: 38.6431,
    lng: 34.8303,
    country: "Turkey",
    description: "Fairy chimneys and hot air balloon flights",
  },
  {
    name: "Serengeti",
    lat: -2.154,
    lng: 34.6857,
    country: "Tanzania",
    description: "Vast ecosystem hosting the great migration",
  },
  {
    name: "Ha Long Bay",
    lat: 20.9101,
    lng: 107.1839,
    country: "Vietnam",
    description: "Emerald waters and thousands of limestone islands",
  },
  {
    name: "Chichen Itza",
    lat: 20.6843,
    lng: -88.5678,
    country: "Mexico",
    description: "Ancient Mayan city in the Yucatán Peninsula",
  },
  {
    name: "Neuschwanstein Castle",
    lat: 47.5576,
    lng: 10.7498,
    country: "Germany",
    description: "19th-century Romanesque Revival palace",
  },
  {
    name: "Kyoto",
    lat: 35.0116,
    lng: 135.7681,
    country: "Japan",
    description: "Former imperial capital with 2,000+ temples",
  },
  {
    name: "Patagonia",
    lat: -50.9423,
    lng: -73.4068,
    country: "Argentina / Chile",
    description: "Wilderness region of glaciers and peaks",
  },
  {
    name: "Marrakech Medina",
    lat: 31.6295,
    lng: -7.9811,
    country: "Morocco",
    description: "Historic walled city with souks and palaces",
  },
  {
    name: "Galápagos Islands",
    lat: -0.9538,
    lng: -90.9656,
    country: "Ecuador",
    description: "Volcanic archipelago with unique wildlife",
  },
  {
    name: "Uluru",
    lat: -25.3444,
    lng: 131.0369,
    country: "Australia",
    description: "Sacred sandstone monolith in the Outback",
  },
  {
    name: "Prague Old Town",
    lat: 50.0755,
    lng: 14.4378,
    country: "Czech Republic",
    description: "Medieval square with astronomical clock",
  },
];
