export type VisaStatus = "visa-free" | "e-visa" | "visa-on-arrival" | "visa-required" | "eta";

export interface DestinationCountry {
  code: string;
  name: string;
  portalUrl: string;
  policies: Record<string, VisaStatus>; // Passport Code -> Status
}

export const passportList = [
  { code: "US", name: "United States" },
  { code: "GB", name: "United Kingdom" },
  { code: "EU", name: "Schengen Area (EU)" },
  { code: "CA", name: "Canada" },
  { code: "AU", name: "Australia" },
  { code: "IN", name: "India" },
  { code: "CN", name: "China" },
  { code: "RU", name: "Russia" },
  { code: "BR", name: "Brazil" },
  { code: "JP", name: "Japan" },
];

export const destinations: DestinationCountry[] = [
  {
    code: "US",
    name: "United States",
    portalUrl: "https://travel.state.gov/content/travel/en/us-visas.html",
    policies: {
      GB: "eta",
      EU: "eta",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-required",
      JP: "eta",
    },
  },
  {
    code: "GB",
    name: "United Kingdom",
    portalUrl: "https://www.gov.uk/browse/visas-immigration",
    policies: {
      US: "eta",
      EU: "eta",
      CA: "eta",
      AU: "eta",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "eta",
    },
  },
  {
    code: "FR",
    name: "France",
    portalUrl: "https://france-visas.gouv.fr/en/",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "DE",
    name: "Germany",
    portalUrl: "https://www.auswaertiges-amt.de/en/visa-service",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "IT",
    name: "Italy",
    portalUrl: "https://vistoperitalia.esteri.it/home.aspx",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "ES",
    name: "Spain",
    portalUrl: "https://www.exteriores.gob.es/En/Embajadas/madrid/Paginas/SolicitarVisado.aspx",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "NL",
    name: "Netherlands",
    portalUrl: "https://ind.nl/en",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "CH",
    name: "Switzerland",
    portalUrl: "https://www.sem.admin.ch/sem/en/home/themen/einreise_visa.html",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    portalUrl: "https://smartservices.icp.gov.ae/",
    policies: {
      US: "visa-on-arrival",
      GB: "visa-on-arrival",
      EU: "visa-on-arrival",
      CA: "visa-on-arrival",
      AU: "visa-on-arrival",
      IN: "e-visa",
      CN: "visa-on-arrival",
      RU: "visa-on-arrival",
      BR: "visa-on-arrival",
      JP: "visa-on-arrival",
    },
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    portalUrl: "https://visa.visitsaudi.com/",
    policies: {
      US: "e-visa",
      GB: "e-visa",
      EU: "e-visa",
      CA: "e-visa",
      AU: "e-visa",
      IN: "e-visa",
      CN: "e-visa",
      RU: "e-visa",
      BR: "e-visa",
      JP: "e-visa",
    },
  },
  {
    code: "SG",
    name: "Singapore",
    portalUrl: "https://www.ica.gov.sg/",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-free",
      RU: "e-visa",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "JP",
    name: "Japan",
    portalUrl: "https://www.mofa.go.jp/j_info/visit/visa/",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-free",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "CN",
    name: "China",
    portalUrl: "https://www.visaforchina.cn/",
    policies: {
      US: "visa-required",
      GB: "visa-required",
      EU: "visa-required",
      CA: "visa-required",
      AU: "visa-required",
      IN: "visa-required",
      CN: "visa-free",
      RU: "visa-free",
      BR: "visa-required",
      JP: "visa-required",
    },
  },
  {
    code: "IN",
    name: "India",
    portalUrl: "https://indianvisaonline.gov.in/evisa/tvoa.html",
    policies: {
      US: "e-visa",
      GB: "e-visa",
      EU: "e-visa",
      CA: "e-visa",
      AU: "e-visa",
      IN: "visa-free",
      CN: "visa-required",
      RU: "e-visa",
      BR: "e-visa",
      JP: "e-visa",
    },
  },
  {
    code: "TR",
    name: "Turkey",
    portalUrl: "https://www.evisa.gov.tr/en/",
    policies: {
      US: "e-visa",
      GB: "e-visa",
      EU: "e-visa",
      CA: "e-visa",
      AU: "e-visa",
      IN: "e-visa",
      CN: "e-visa",
      RU: "visa-free",
      BR: "visa-free",
      JP: "e-visa",
    },
  },
  {
    code: "BR",
    name: "Brazil",
    portalUrl: "http://www.itamaraty.gov.br/en/series-722578562d7f7/visas",
    policies: {
      US: "visa-required",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "e-visa",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-free",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "RU",
    name: "Russia",
    portalUrl: "https://electronic-visa.kdmid.ru/",
    policies: {
      US: "visa-required",
      GB: "visa-required",
      EU: "visa-required",
      CA: "visa-required",
      AU: "visa-required",
      IN: "e-visa",
      CN: "visa-free",
      RU: "visa-free",
      BR: "visa-free",
      JP: "visa-required",
    },
  },
  {
    code: "MX",
    name: "Mexico",
    portalUrl: "https://www.gob.mx/inm",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "EG",
    name: "Egypt",
    portalUrl: "https://www.visa2egypt.gov.eg/",
    policies: {
      US: "e-visa",
      GB: "visa-on-arrival",
      EU: "visa-on-arrival",
      CA: "visa-on-arrival",
      AU: "visa-on-arrival",
      IN: "e-visa",
      CN: "visa-on-arrival",
      RU: "visa-on-arrival",
      BR: "visa-on-arrival",
      JP: "visa-on-arrival",
    },
  },
  {
    code: "ZA",
    name: "South Africa",
    portalUrl: "http://www.dha.gov.za/index.php/immigration-services/types-of-visas",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "TH",
    name: "Thailand",
    portalUrl: "https://www.thaievisa.go.th/",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-free",
      CN: "visa-free",
      RU: "visa-free",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "ID",
    name: "Indonesia",
    portalUrl: "https://molina.imigrasi.go.id/",
    policies: {
      US: "visa-on-arrival",
      GB: "visa-on-arrival",
      EU: "visa-on-arrival",
      CA: "visa-on-arrival",
      AU: "visa-on-arrival",
      IN: "visa-on-arrival",
      CN: "visa-on-arrival",
      RU: "visa-on-arrival",
      BR: "visa-on-arrival",
      JP: "visa-on-arrival",
    },
  },
  {
    code: "MY",
    name: "Malaysia",
    portalUrl: "https://www.imi.gov.my/",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "e-visa",
      CN: "visa-free",
      RU: "e-visa",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "KR",
    name: "South Korea",
    portalUrl: "https://www.hikorea.go.kr/",
    policies: {
      US: "eta",
      GB: "eta",
      EU: "eta",
      CA: "eta",
      AU: "eta",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-free",
      BR: "eta",
      JP: "visa-free",
    },
  },
  {
    code: "NZ",
    name: "New Zealand",
    portalUrl: "https://www.immigration.govt.nz/",
    policies: {
      US: "eta",
      GB: "eta",
      EU: "eta",
      CA: "eta",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "eta",
    },
  },
  {
    code: "PT",
    name: "Portugal",
    portalUrl: "https://vistos.mne.gov.pt/en/",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "QA",
    name: "Qatar",
    portalUrl: "https://hayya.qa/",
    policies: {
      US: "eta",
      GB: "eta",
      EU: "eta",
      CA: "eta",
      AU: "eta",
      IN: "e-visa",
      CN: "e-visa",
      RU: "e-visa",
      BR: "eta",
      JP: "eta",
    },
  },
  {
    code: "AR",
    name: "Argentina",
    portalUrl: "https://www.argentina.gob.ar/interior/migraciones",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "e-visa",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-free",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "AU",
    name: "Australia",
    portalUrl: "https://immi.homeaffairs.gov.au/",
    policies: {
      US: "eta",
      GB: "eta",
      EU: "eta",
      CA: "eta",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "e-visa",
      JP: "eta",
    },
  },
  {
    code: "CA",
    name: "Canada",
    portalUrl: "https://www.canada.ca/en/immigration-refugees-citizenship.html",
    policies: {
      US: "visa-free",
      GB: "eta",
      EU: "eta",
      CA: "visa-free",
      AU: "eta",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "e-visa",
      JP: "eta",
    },
  },
  {
    code: "BE",
    name: "Belgium",
    portalUrl: "https://dofi.ibz.be/",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "AT",
    name: "Austria",
    portalUrl: "https://www.bmeia.gv.at/en/oeb-mission",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "GR",
    name: "Greece",
    portalUrl: "https://www.mfa.gr/en/visas/",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "IE",
    name: "Ireland",
    portalUrl: "https://www.irishimmigration.ie/",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "PL",
    name: "Poland",
    portalUrl: "https://www.gov.pl/web/diplomacy/visas",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "SE",
    name: "Sweden",
    portalUrl: "https://www.migrationsverket.se/",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "NO",
    name: "Norway",
    portalUrl: "https://www.udi.no/en/",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "DK",
    name: "Denmark",
    portalUrl: "https://www.nyidanmark.dk/en-GB",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "FI",
    name: "Finland",
    portalUrl: "https://um.fi/visa-requirements",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-free",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "CZ",
    name: "Czech Republic",
    portalUrl: "https://www.mzv.cz/jnp/en/information_for_aliens/index.html",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "HU",
    name: "Hungary",
    portalUrl: "https://konzuliszolgalat.kormany.hu/en",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "RO",
    name: "Romania",
    portalUrl: "https://www.mae.ro/en/node/2035",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "BG",
    name: "Bulgaria",
    portalUrl: "https://www.mfa.bg/en/services-travel/visas",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "HR",
    name: "Croatia",
    portalUrl: "https://mvep.gov.hr/consular-information/visas-28779",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "IL",
    name: "Israel",
    portalUrl: "https://www.gov.il/en/departments/units/visa_department",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-free",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "CL",
    name: "Chile",
    portalUrl: "https://consulado.gob.cl/",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "e-visa",
      CN: "visa-required",
      RU: "visa-free",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "CO",
    name: "Colombia",
    portalUrl: "https://www.cancilleria.gov.co/",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-free",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "PE",
    name: "Peru",
    portalUrl: "https://www.gob.pe/migraciones",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-free",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "VE",
    name: "Venezuela",
    portalUrl: "https://www.saime.gob.ve/",
    policies: {
      US: "visa-required",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-free",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "UY",
    name: "Uruguay",
    portalUrl: "https://www.migracion.gub.uy/",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-free",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "EC",
    name: "Ecuador",
    portalUrl: "https://www.cancilleria.gob.ec/",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-free",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "PY",
    name: "Paraguay",
    portalUrl: "https://www.mre.gov.py/",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-free",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
  {
    code: "BO",
    name: "Bolivia",
    portalUrl: "https://www.rree.gob.bo/",
    policies: {
      US: "visa-on-arrival",
      GB: "visa-on-arrival",
      EU: "visa-on-arrival",
      CA: "visa-on-arrival",
      AU: "visa-on-arrival",
      IN: "e-visa",
      CN: "visa-required",
      RU: "visa-on-arrival",
      BR: "visa-free",
      JP: "visa-on-arrival",
    },
  },
  {
    code: "VN",
    name: "Vietnam",
    portalUrl: "https://evisa.xuatnhapcanh.gov.vn/",
    policies: {
      US: "e-visa",
      GB: "e-visa",
      EU: "e-visa",
      CA: "e-visa",
      AU: "e-visa",
      IN: "e-visa",
      CN: "visa-free",
      RU: "visa-free",
      BR: "e-visa",
      JP: "e-visa",
    },
  },
  {
    code: "KH",
    name: "Cambodia",
    portalUrl: "https://www.evisa.gov.kh/",
    policies: {
      US: "e-visa",
      GB: "e-visa",
      EU: "e-visa",
      CA: "e-visa",
      AU: "e-visa",
      IN: "e-visa",
      CN: "visa-free",
      RU: "e-visa",
      BR: "e-visa",
      JP: "e-visa",
    },
  },
  {
    code: "MM",
    name: "Myanmar",
    portalUrl: "https://evisa.moip.gov.mm/",
    policies: {
      US: "e-visa",
      GB: "e-visa",
      EU: "e-visa",
      CA: "e-visa",
      AU: "e-visa",
      IN: "e-visa",
      CN: "e-visa",
      RU: "e-visa",
      BR: "e-visa",
      JP: "e-visa",
    },
  },
  {
    code: "LK",
    name: "Sri Lanka",
    portalUrl: "https://www.eta.gov.lk/",
    policies: {
      US: "eta",
      GB: "eta",
      EU: "eta",
      CA: "eta",
      AU: "eta",
      IN: "eta",
      CN: "e-visa",
      RU: "e-visa",
      BR: "eta",
      JP: "eta",
    },
  },
  {
    code: "PK",
    name: "Pakistan",
    portalUrl: "https://visa.nadra.gov.pk/",
    policies: {
      US: "e-visa",
      GB: "e-visa",
      EU: "e-visa",
      CA: "e-visa",
      AU: "e-visa",
      IN: "e-visa",
      CN: "e-visa",
      RU: "e-visa",
      BR: "e-visa",
      JP: "e-visa",
    },
  },
  {
    code: "BD",
    name: "Bangladesh",
    portalUrl: "https://www.visa.gov.bd/",
    policies: {
      US: "visa-on-arrival",
      GB: "visa-on-arrival",
      EU: "visa-on-arrival",
      CA: "visa-on-arrival",
      AU: "visa-on-arrival",
      IN: "visa-free",
      CN: "visa-on-arrival",
      RU: "visa-on-arrival",
      BR: "visa-on-arrival",
      JP: "visa-on-arrival",
    },
  },
  {
    code: "NP",
    name: "Nepal",
    portalUrl: "https://nepalimmigration.gov.np/",
    policies: {
      US: "visa-on-arrival",
      GB: "visa-on-arrival",
      EU: "visa-on-arrival",
      CA: "visa-on-arrival",
      AU: "visa-on-arrival",
      IN: "visa-free",
      CN: "visa-on-arrival",
      RU: "visa-on-arrival",
      BR: "visa-on-arrival",
      JP: "visa-on-arrival",
    },
  },
  {
    code: "KE",
    name: "Kenya",
    portalUrl: "https://evisa.go.ke/",
    policies: {
      US: "e-visa",
      GB: "e-visa",
      EU: "e-visa",
      CA: "e-visa",
      AU: "e-visa",
      IN: "e-visa",
      CN: "e-visa",
      RU: "e-visa",
      BR: "e-visa",
      JP: "e-visa",
    },
  },
  {
    code: "NG",
    name: "Nigeria",
    portalUrl: "https://immigration.gov.ng/",
    policies: {
      US: "visa-on-arrival",
      GB: "visa-required",
      EU: "visa-required",
      CA: "visa-required",
      AU: "visa-required",
      IN: "visa-required",
      CN: "visa-required",
      RU: "visa-required",
      BR: "visa-required",
      JP: "visa-required",
    },
  },
  {
    code: "MA",
    name: "Morocco",
    portalUrl: "https://www.consulat.ma/",
    policies: {
      US: "visa-free",
      GB: "visa-free",
      EU: "visa-free",
      CA: "visa-free",
      AU: "visa-free",
      IN: "e-visa",
      CN: "visa-free",
      RU: "visa-free",
      BR: "visa-free",
      JP: "visa-free",
    },
  },
];

export function getVisaStatus(passport: string, destination: DestinationCountry): VisaStatus {
  return destination.policies[passport] || "visa-required";
}
