// Wikidata QIDs for countries — used to query current officeholders live.
// QIDs are stable, well-established Wikidata identifiers that don't change.
// To add more countries: add one line here. No other code changes needed.
export interface CountryRegistryEntry {
  code: string; // ISO 3166-1 alpha-2
  name: string;
  wikidataId: string; // e.g. "Q30" for United States
}

export const countryRegistry: CountryRegistryEntry[] = [
  { code: "US", name: "United States", wikidataId: "Q30" },
  { code: "CN", name: "China", wikidataId: "Q148" },
  { code: "IN", name: "India", wikidataId: "Q668" },
  { code: "RU", name: "Russia", wikidataId: "Q159" },
  { code: "GB", name: "United Kingdom", wikidataId: "Q145" },
  { code: "FR", name: "France", wikidataId: "Q142" },
  { code: "DE", name: "Germany", wikidataId: "Q183" },
  { code: "JP", name: "Japan", wikidataId: "Q17" },
  { code: "BR", name: "Brazil", wikidataId: "Q155" },
  { code: "ZA", name: "South Africa", wikidataId: "Q258" },
  { code: "SA", name: "Saudi Arabia", wikidataId: "Q851" },
  { code: "IR", name: "Iran", wikidataId: "Q794" },
  { code: "IL", name: "Israel", wikidataId: "Q801" },
  { code: "TR", name: "Turkey", wikidataId: "Q43" },
  { code: "UA", name: "Ukraine", wikidataId: "Q212" },
  { code: "KP", name: "North Korea", wikidataId: "Q423" },
  { code: "KR", name: "South Korea", wikidataId: "Q884" },
  { code: "TW", name: "Taiwan", wikidataId: "Q865" },
  { code: "PK", name: "Pakistan", wikidataId: "Q843" },
  { code: "EG", name: "Egypt", wikidataId: "Q79" },
  { code: "NG", name: "Nigeria", wikidataId: "Q1033" },
  { code: "AU", name: "Australia", wikidataId: "Q408" },
  { code: "CA", name: "Canada", wikidataId: "Q16" },
  { code: "MX", name: "Mexico", wikidataId: "Q96" },
  { code: "AE", name: "United Arab Emirates", wikidataId: "Q878" },
  { code: "IT", name: "Italy", wikidataId: "Q38" },
  { code: "ES", name: "Spain", wikidataId: "Q29" },
  { code: "ID", name: "Indonesia", wikidataId: "Q252" },
  { code: "AR", name: "Argentina", wikidataId: "Q414" },
  { code: "NL", name: "Netherlands", wikidataId: "Q55" },
  { code: "SE", name: "Sweden", wikidataId: "Q34" },
  { code: "CH", name: "Switzerland", wikidataId: "Q39" },
  { code: "PL", name: "Poland", wikidataId: "Q36" },
  { code: "BE", name: "Belgium", wikidataId: "Q31" },
  { code: "TH", name: "Thailand", wikidataId: "Q869" },
  { code: "VN", name: "Vietnam", wikidataId: "Q881" },
  { code: "PH", name: "Philippines", wikidataId: "Q928" },
  { code: "MY", name: "Malaysia", wikidataId: "Q833" },
  { code: "SG", name: "Singapore", wikidataId: "Q334" },
  { code: "NZ", name: "New Zealand", wikidataId: "Q664" },
  { code: "QA", name: "Qatar", wikidataId: "Q846" },
  { code: "KW", name: "Kuwait", wikidataId: "Q817" },
  { code: "JO", name: "Jordan", wikidataId: "Q810" },
  { code: "LB", name: "Lebanon", wikidataId: "Q822" },
  { code: "SY", name: "Syria", wikidataId: "Q858" },
  { code: "IQ", name: "Iraq", wikidataId: "Q796" },
  { code: "AF", name: "Afghanistan", wikidataId: "Q889" },
  { code: "MM", name: "Myanmar", wikidataId: "Q836" },
  { code: "BD", name: "Bangladesh", wikidataId: "Q902" },
  { code: "LK", name: "Sri Lanka", wikidataId: "Q854" },
  { code: "NP", name: "Nepal", wikidataId: "Q837" },
  { code: "ET", name: "Ethiopia", wikidataId: "Q115" },
  { code: "KE", name: "Kenya", wikidataId: "Q114" },
  { code: "GH", name: "Ghana", wikidataId: "Q117" },
  { code: "DZ", name: "Algeria", wikidataId: "Q262" },
  { code: "MA", name: "Morocco", wikidataId: "Q1028" },
  { code: "CO", name: "Colombia", wikidataId: "Q739" },
  { code: "CL", name: "Chile", wikidataId: "Q298" },
  { code: "PE", name: "Peru", wikidataId: "Q419" },
  { code: "VE", name: "Venezuela", wikidataId: "Q717" },
  { code: "CU", name: "Cuba", wikidataId: "Q241" },
  { code: "GR", name: "Greece", wikidataId: "Q41" },
  { code: "PT", name: "Portugal", wikidataId: "Q45" },
  { code: "NO", name: "Norway", wikidataId: "Q20" },
  { code: "FI", name: "Finland", wikidataId: "Q33" },
  { code: "DK", name: "Denmark", wikidataId: "Q35" },
  { code: "IE", name: "Ireland", wikidataId: "Q27" },
  { code: "AT", name: "Austria", wikidataId: "Q40" },
  { code: "HU", name: "Hungary", wikidataId: "Q28" },
  { code: "CZ", name: "Czech Republic", wikidataId: "Q213" },
  { code: "RO", name: "Romania", wikidataId: "Q218" },
];
